#!/bin/sh
### BEGIN INIT INFO
# Provides:          r10k_payload_deploy
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: accepts payloads from github and deploys environments to mcollective/puppetmasters
# Description:
### END INIT INFO

#
# Author: Ørjan Ommundsen <orjan@redpill-linpro.com>
#

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="r10k payload deploy"
NAME=r10k_payload_deploy

PIDFILE=/var/run/${NAME}.pid

DAEMON=/opt/r10k_payload_deploy/app.rb

SCRIPTNAME=/etc/init.d/$NAME

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# expose to ruby
export PORT BIND SSL_CRT SSL_KEY LOGFILE PIDFILE

# Define LSB log_* functions.
. /lib/lsb/init-functions

do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   other if daemon could not be started or a failure occured
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON $CONFFILE
}

do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   other if daemon could not be stopped or a failure occurred
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC"
	do_start
	case "$?" in
		0) log_end_msg 0 ;;
		*) log_end_msg 1 ;;
	esac
	;;
  stop)
	log_daemon_msg "Stopping $DESC"
	do_stop
	case "$?" in
		0) log_end_msg 0 ;;
		*) log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	$0 stop
	sleep 2
	$0 start
	;;
  status)
	status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
	exit 3
	;;
esac

